# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/


# Assets
statics: / #//cdn.jsdelivr.net/gh/username/RepositoryName@latest/
css: css
js: js
# assets代替了之前的image选项
assets: "assets"

# Dark Mode
# By default, the page judges whether to turn on the dark mode according to the device settings or user selection
# if `true`, the page will be displayed directly as Dark Mode, unless the user makes another choice
darkmode: #true

# By default the page will automatically scroll to the last viewed position
# if `false`, automatic positioning will be turned off
auto_scroll: true


menu:
  home: / || home
  about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  # friends: /friends/ || heart
  links: /links/ || magic

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/ToelUl || github || "#191717"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

sidebar:
  # Sidebar Position.
  position: left
  # position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar_2.jpg

widgets:
  # if true, will show random posts
  random_posts: true
  # if true, will show recent comments
  recent_comments: true

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2023
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true

post:
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------
# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
# meta_generator: true

# seo: # 下方直接填入对应meta的content即可
#   bing: 
#   google: 
#   yandex:
#   baidu:

# visitor:
#   baiduAnalytics: # 百度统计代码中的?后部分

# baidu_analytics: # <app_id>

# # Disable Baidu transformation on mobile devices.
# disable_baidu_transformation: true

# # Automatically add external URL with Base64 encrypt & decrypt.
# exturl: true

# # Google Webmaster tools verification.
# # See: https://www.google.com/webmasters
# google_site_verification:

# # Bing Webmaster tools verification.
# # See: https://www.bing.com/webmaster
# bing_site_verification:

# # Yandex Webmaster tools verification.
# # See: https://webmaster.yandex.ru
# yandex_site_verification:

# # Baidu Webmaster tools verification.
# # See: https://ziyuan.baidu.com/site
# baidu_site_verification:

# # Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO.
# baidu_push: false

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment

experiments:
  optimizeLongPosts: true # 开启长文章优化

