# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

alternate: Physics # 站点大标题
# Assets
statics: / #//cdn.jsdelivr.net/gh/username/RepositoryName@latest/
css: css
js: js
# assets代替了之前的image选项
assets: "assets"

# Dark Mode
# By default, the page judges whether to turn on the dark mode according to the device settings or user selection
# if `true`, the page will be displayed directly as Dark Mode, unless the user makes another choice
darkmode: #true

# By default the page will automatically scroll to the last viewed position
# if `false`, automatic positioning will be turned off
auto_scroll: true

# menu:
#   home: / || home
#   about: /about/ || user
#   submenu:
#     default: /page/ || user
#     link: /page1/ || cloud
#   link2: /page2/ || coffee
  
menu:
  home: / || home
  about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  # friends: /friends/ || heart
  links: /links/ || magic

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/ToelUl || github || "#191717"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

sidebar:
  # Sidebar Position.
  position: left
  # position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.jpg

widgets:
  # if true, will show random posts
  random_posts: true
  # if true, will show recent comments
  recent_comments: false

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2023
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true

post:
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true

# bgm
audio:
 - title: 列表1
   list:
    - https://music.163.com/#/song?id=469772
    - https://music.163.com/#/song?id=469742
    - https://music.163.com/#/song?id=469933
    - https://music.163.com/#/song?id=469868
    - https://music.163.com/#/song?id=469821
    - https://music.163.com/#/song?id=29482202
    - https://music.163.com/#/song?id=30569548
    #  - https://music.163.com/#/song?id=2034742057
#      - https://music.163.com/#/playlist?id=2297706586
#   - title: 列表2
#     list:
#      - https://music.163.com/#/playlist?id=2031842656

# 实验性特性
experiments:
  noIE: true # TODO 阻止IE浏览器访问(ShokaX不支持IE的任何版本)
  noPlayer: false # 禁用音乐播放器
  gradient: false # 使用CSS渐变作为文章封面
  fixedCover: "" # 主页面cover(为空则使用bing随机图片)
  debug: false # 使用debug模式启动
  disableThemeComment: false # 禁用主题评论系统(一般用于关闭评论或让插件接管评论系统)
  usingRelative: false # _image.yml 使用相对路径
  optimizeLongPosts: false # 优化长文章，这能让长文章的FPS提升70%-150%并解决假死问题，但存在一些副作用
  # 具体见https://docs.kaitaku.xyz/guide/theme.html#%E9%95%BF%E6%96%87%E7%AB%A0%E4%BC%98%E5%8C%96
  mobileWidth: 820px # 移动版和桌面版导航栏最短切换长度

